# syntax=docker/dockerfile:1
FROM python:3.8.10

WORKDIR /code

COPY src/ .

COPY requirements.txt .

ENV FLASK_APP=api.py

ENV FLASK_ENV=development

RUN pip install -r requirements.txt

EXPOSE 5000

CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]